[package]
name = "recursion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "countdown"
path = "src/countdown.rs"

[[bin]]
name = "factorial"
path = "src/factorial.rs"

[dependencies]
